### ISSUE TITLE
Comment pane extends outside element on mobile

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#511] opened 2022-01-15 01:17 UTC
Steps to reproduce:

- Go to the comment pane on a bucket on mobile 
- Swipe to the left

Result:

Comment tool seems to invisibly extend to the right, making the container div at least twice as large as it should be

**Comment by Powersource** [comment] 2022-01-15 01:28
Hmm only reproducibile in chrome.

And at least this seems to be the only visual bug, the editor is still contained where it should be etc

**Comment by aerugo** [comment] 2022-01-15 19:29
I noticed this problem on iOS Safari, so possible it only works fully as expected on Firefox.

**Comment by aerugo** [comment] 2022-01-18 16:43
Did you test in an iOS safari emulator? 
Still a problem on my side. Tried logging in a new incognito tab.

**Comment by Powersource** [comment] 2022-01-18 16:45
i don't think i have access to one of those, tried in chrome though. very strange. try hard-refreshing (however you do that)

**Comment by aerugo** [comment] 2022-01-18 16:55
I just tried on Safari on Mac, and the problem is there. Chrome works as expected.

**Comment by Powersource** [comment] 2022-01-18 17:18
gonna hand this over to Gustav instead

**Comment by gustavlrsn** [comment] 2022-01-19 12:40
Pushed a fix, seems to work now

**Closed by gustavlrsn** 2022-01-19 12:40 UTC
