### ISSUE TITLE
[BUG] Buckets that have reached goal should not filter as “open for funding”

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#705] opened 2022-05-03 09:20 UTC
**Describe the bug**

![D9B585F9-7092-4B65-9B25-E1EA76180F57](https://user-images.githubusercontent.com/7785081/166430268-c4225f60-0e45-406a-aad3-da2892940b61.jpeg)

**To Reproduce**
Go to a round with buckets that have reached their goal and filter on open for funding.

**Expected behavior**
I should not see buckets that have reached their goal as these are not fundable.

**Comment by gustavlrsn** [comment] 2022-05-05 12:20
Part of the issue is that `fundedAt` was never set in the migration. I'll try to get the `Accept funding` button to appear so that you can manually set these as funded.

But then the filtering seems pretty broken also. Looking into it

**Comment by gustavlrsn** [comment] 2022-05-05 12:34
Pushed a fix now to at make sure to show the accept funding button if the min goal has been reached (there was some other unnecessary conditions on showing it).

**Closed** 2022-05-06 12:02 UTC
