### ISSUE TITLE
Invalid criteria when signing up

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#226] opened 2020-09-05 10:27 UTC
A member of the cobudget group institute for evolutionary leadership sent a message saying: 

_it says invalid criteria for log in
tried twice to set up new password_

**Comment by gardner** [comment] 2020-09-05 11:54
I was able to change my password to a new password that contains a lowercase, uppercase, number, and symbol.

When I try to set it to an all lowercase word, then I get the following error: 

![image](https://user-images.githubusercontent.com/787026/92304538-f91fc180-efd2-11ea-95b2-c6d3cf628fac.png)

The update password behaviour should be updated to prevent submitting a password that doesn't conform to the new guidelines. 

Can you please ask them for clarification @francesca-sp ? Thanks

**Comment by francesca-sp** [comment] 2020-09-24 12:55
We have received 3 more messages from users, all saying a version of: "My password meets all criteria but the page does not advance to next step in process of setting up account."

**Comment by francesca-sp** [comment] 2020-09-25 09:58
One of the users got back to me and shared:

**Comment by gardner** [comment] 2020-10-01 01:32
I am unable to reproduce this when creating a new account.
![image](https://user-images.githubusercontent.com/787026/94756033-e1c9cd80-03f2-11eb-8d41-1281670ca2ee.png)

**Comment by gardner** [comment] 2020-10-01 17:19
This is the front-end password regex:

```
ng-pattern="/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{10,}$/"
```

That means special characters are considered to be: `@$!%*?&`

I will update the message in the UI to reflect this.

**Comment by gardner** [comment] 2020-10-06 18:38
A fix for this has been deployed.

**Closed by gardner** 2020-10-06 18:38 UTC
