### ISSUE TITLE
[FEATURE] List view of buckets

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#727] opened 2022-05-20 07:45 UTC
**Describe the feature**
I know @aerugo is already working on implementing this for BL, but it is becoming an important feature for MT as well. It is next to impossible to get an overview over a round if it has more than ~24 dreams. This make the admin work very hard, and forces the user to export bucket data to excel. This data is not kept up to date, which creates plenty of extra admin work. A list view showing bucket status, funding, and some other info is needed.

**Comment by aerugo** [comment] 2022-06-01 22:41
Duplicate of #306

**Closed by aerugo** 2022-06-01 22:41 UTC
