### ISSUE TITLE
[BUG] Display issues with Org/Round Switcher

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#584] opened 2022-03-01 15:47 UTC
**Describe the bug**

I've found 2 issues with the implementation of the org switcher developed here https://github.com/cobudget/cobudget/issues/415 

* I uploaded a square image as a logo for the Enspiral group, and the logo gets distorted in the group/round selector dropdown. It looks fine though when I am on the group main page (not inside a round)

See screenshots:
![image](https://user-images.githubusercontent.com/3641828/156201456-a9072ac0-11b5-4995-9a8f-4cd9563afdbf.png)
![image](https://user-images.githubusercontent.com/3641828/156201416-915cd191-d697-49a7-8eda-9560a6fd2fc8.png)

When clicking into a round inside a group, the Group name gets almost totally cut off and there are [...] instead.
See screenshot:
![image](https://user-images.githubusercontent.com/3641828/156201381-5012ecd7-5ba1-4efe-88fa-9d91ecee3e54.png)

Browser: Chrome
Device: Windows

**Comment by Powersource** [comment] 2022-03-07 12:56
The enspiral image doesn't actually seem to be entirely square https://res.cloudinary.com/dreamswtf/image/upload/v1645033711/org_logos/kmz5zwqcpcq7dlmxwleg.png which makes sense since I could only reproduce this with a rectangular image. Need to handle this correctly in both cases.

**Comment by Powersource** [comment] 2022-03-07 15:30
for the second bug, if i change the round name to something a bit longer then it somehow decides to truncate the group name later so you see more of it :thinking: weird browser rendering stuff

**Comment by Powersource** [comment] 2022-03-09 14:47
both should be fixed now

**Comment by tomomiq** [comment] 2022-03-10 15:39
LGTM 

<img width="542" alt="Screenshot 2022-03-10 at 16 38 12" src="https://user-images.githubusercontent.com/1287179/157697402-72719f04-60f2-48bf-b9c0-adc3d28dbad0.png">

**Closed by tomomiq** 2022-03-10 15:39 UTC
Labels: needs testing
